project:
  type: default
  output-dir: _publish
engine: knitr
jupyter: python3
bibliography: psha/_bib/references.bib
link-citations: true
colorlinks: true
fontsize: 12pt
citation: false
appendix-cite-as: display
google-scholar: false
execute:
  eval: true
  echo: false
  include: false
  keep-md: false
  freeze: false
format:
  revealjs:
    output-file: index.html
    theme: simple
    margin: 0
    center: false
    revealOptions:
      width: 1920
      height: 720
      autoScale: false
    scrollable: true
    controls: true
    progress: true
    keyboard: true
    touch: true
    hash: true
    loop: false
    history: false
    transition: fade
    transition-speed: default
    background-transition: fade
    fragments: true
    fragment-in-url: true
    highlight-style: dracula
    code-line-numbers: true
    code-copy: true
    code-overflow: scroll
    slide-number: c/t
    footer: ''
    plugins:
    - search
    - chalkboard
    - zoom
    - menu
    chalkboard: true
    search: true
    menu: true
    zoom: true
    title-slide: false
    logo: psha/css/logo.png
    css: psha/css/styles.css
toc-title: Table of Contents
crossref:
  fig-title: Fig.
  tbl-title: Table
  eq-title: Equation
  eq-prefix: eq.
  tbl-prefix: tbl.
  fig-prefix: fig.
params:
  background: white
  render: none
  ext: png
  lang: EN

