---
title: ""
number-sections: false
toc: false
listing: false
---


```{r setup,echo=FALSE,include=TRUE,eval=TRUE,message=FALSE}
root <- normalizePath(file.path(here::here(), ".."))
psha_path <- file.path(root, "html", "psha")
source(file.path(psha_path,"R","run.R"))
# ID_gmdp <- "max"
# quarto render
# netlify sites:create --manual
# netlify deploy --prod --dir=_publish
```



{{< include _slides/cover.qmd >}}

## <br>PNG Regional Hazard

> **ATC/W response:** *We are not aware of any published studies that indicate a PGA in excess of 0.90g for an AEP of 1:475 at the TSF location. Please provide the above-mentioned published study that supports this claim.*

The seismic sources referenced by K92 are the **Ramu–Markham Fault System (RMFS)**, located within 15 km of the tailings facility and capable of full-segment ruptures with magnitudes Mw 8.1–8.3 [@Wallace2021], and the **New Britain (NB) subduction interface**, known to have produced megathrust events with magnitudes ranging from Mw 8.0 to 8.8 [@USGS2007]. Published studies reporting PGA values close to 0.90g for the region include those by [@Ghasemi2020] and the GEM seismic hazard model documentation for Papua New Guinea [@GEM2023], available online here: ([PDF](https://hazard.openquake.org/gem/pdf/png-report.pdf)). The K92 comment stands.

## <br>PNG Regional Hazard

> **ATC/W response:** *Unless we find more convincing data that $M_{\max}$ for the faults surrounding the site considered in this analysis are higher, we believe that the PSHA results developed by ATCW (2020) are still valid. Therefore, we assess that there is no need to reassess the seismic hazard at the site at present.*

An independent probabilistic seismic hazard analysis was conducted by SRK at the TSF coordinates using the Papua New Guinea seismic hazard logic tree developed by the Global Earthquake Model [@GEM2023]. The internal details of the ATC/W logic tree—such as source-zone definitions, recurrence parameters, GMPE selection, and their assigned weights—are not publicly disclosed. Details of the ground motion equations, sources and  logic trees from the GEM 2020 Hazard model, ara available in this [URL](https://www.globalquakemodel.org/product/papua-new-guinea-hazard). The independent analysis resulted in a peak ground acceleration (PGA) of **0.63 g** for reference rock $(Vs_{30} \approx 760 m/s)$ at an annual exceedance probability (AEP) of **1/475**. These results are consistent with PGA values (**0.7–1.1 g**) reported by the most recent  ([GEM Global Seismic Hazard Map](https://maps.openquake.org/map/gshm-2023-1/#7/-6.1085/145.8869)) for the Markham–Kainantu region, supporting the benchmark calculation provided.

The PGA adopted by ATC/W—**0.31 g** at AEP of **1/475**—is approximately 50% lower than the independent benchmark calculation (**0.63 g**), and it also lies below the range (**0.59–0.89 g**) indicated by the GEM 2023 model. Therefore, the recommendation from K92 remains valid.

## <br>PNG Regional Hazard

{{< include /_slides/UHS.qmd >}}


## <br>Rupture Size $(M_{\max})$
> **ATC/W response:** *It is worth noting that the Ghasemi et al. (2016) area source model adopted a higher Mmax than those adopted by the DIM-ASIA area source model, i.e. Mmax of 8.0 to 8.8 compared to 7.5 to 8.5. Thus, the Gashemi et al. (2016) model tends to give much higher computed ground accelerations.*

The differences in computed ground accelerations between the Ghasemi et al. [-@Ghasemi2016] and DIM-ASIA [-@DIMASIA2015] area-source models cannot be attributed solely to variations in maximum magnitude ($M_{\max}$). Although higher values of $M_{\max}$ generally lead to larger accelerations, seismic hazard results are also strongly influenced by recurrence intervals, source geometry, segmentation models, rupture characteristics, and particularly by the choice and weighting of Ground Motion Prediction Equations (GMPEs) [@McGuire2004; @Bommer2015]. Recent seismic hazard studies further emphasize that these modeling choices play a critical role in regions characterized by subduction interfaces and large crustal faults, often exceeding the influence of maximum magnitude alone [@Weatherill2016; @Abrahamson2020].


## <br>Ground Motion Prediction Equations (GMPE)

> **ATC/W response:** *We consider shallow and deep crustal earthquakes, as well as subduction earthquakes. We have used the most recent NGA-West Ground Motion Prediction Models (GMPE) with different weights, including Abrahamson et al. (2014), Boore et al. (2014), Cambell & Bozorgnia (2014), BC-Hydro (2012), etc.*

ATC/W states that the seismic hazard analysis incorporates GMPEs for both shallow crustal (NGA-West2) and subduction-zone earthquakes (BC Hydro). Given the proximity of significant seismic sources—including the Ramu–Markham Fault System (RMFS) capable of large crustal earthquakes, and the New Britain subduction megathrust capable of producing Mw $\geq$ 8.0 events—it is critical to confirm that the weighting of these GMPE sets adequately represents regional seismic hazard conditions.

While NGA-West2 models have been extensively validated globally for active shallow crustal regions [@Abrahamson2014; @Boore2014; @Campbell2014], and the BC Hydro subduction GMPE is based on global subduction data [@Abrahamson2016; @Abrahamson2018; @Parker2020], explicit verification of their applicability to Papua New Guinea conditions through residual analyses using regional seismic records is recommended.

However, the author is unaware of the current availability of sufficient strong-motion records from bedrock conditions near these seismic sources, which may pose challenges for conducting such residual analyses. A practical first step could involve reviewing available studies, including those by Ghasemi et al. [-@Ghasemi2016; -@Ghasemi2020], to determine whether appropriate validation or calibration has already been performed or whether additional investigations are necessary.


## <br>Site Response

> **ATC/W response:** *The 2020 seismic study presents the predicted ground motion on rock conditions characterized by Vs = 760 m/sec. Predicting ground motions at sites with significant alluvial soil deposits requires detailed shear-wave velocity (Vs) data, as recommended by K92.*

A benchmark ergodic, nonlinear site-response analysis performed at the TSF coordinates indicates that peak ground acceleration (PGA) values for softer soils (Site Class D) are approximately 40% lower than those computed for rock conditions (Site Class BC). The differences become more pronounced at longer return periods. These results indicate significant nonlinear amplification effects at the TSF location for alluvial soils and larger (SEE) seismic events.

{{< include /_slides/PGA.qmd >}}

## <br>Vertical Ground Motions

> **ATC/W response:** *In dynamic deformation modelling for embankment dams, horizontal ground motion is focused on efficiently addressing the critical risk of failure due to earthquakes. While it is advisable to incorporate vertical ground motion to analyse concrete gravity dams, the impact of vertical motion on the earth and rockfill dams generally is not considered to be significant.*

Routine practice typically focuses dynamic deformation analyses on horizontal ground motions for earth and rockfill dams subjected to moderate-to-strong earthquakes [@USSD2022]. However, FEMA [-@FEMA2015] guidelines indicate that vertical accelerations near active faults can be significant and may even exceed horizontal accelerations. Although neither ANCOLD nor USSD universally requires including vertical motions, both recommend explicitly evaluating vertical ground motions near large faults, either through sensitivity checks or as separate load cases [@USSD2022; @ANCOLD2019].

Considering the proximity of the RMFS, capable of producing earthquakes with $M_{w} \geq 7.5$, explicitly incorporating vertical ground motions into dynamic deformation analyses is appropriate for load cases associated specifically with RMFS seismic events. For these load cases, ensuring realistic vertical spectra and vertical-to-horizontal (V/H) ratios from the ATC/W seismic hazard analysis requires careful validation of the selected GMPEs and their weighting for vertical predictions. On the contrary, vertical ground motions unrelated with the RMFS scenario should not be included.

## <br>Vertical Ground Motions

> **ATC/W response:** *An example from a recent case history of earth and rockfill dams subjected to high horizontal and vertical acceleration is the 156-m high Zipingpu dam in China. It was subjected to horizontal and vertical accelerations of 2.0g. No significant damage was observed (Ishihara, 2012).*


The Zipingpu Dam example cited by ATC/W represents only a single case history and is insufficient for drawing generalized conclusions regarding vertical shaking effects. The deformation response of dams under large events depends strongly on ground motion properties such as shaking duration and frequency content. Reliable assessments require analysis of multiple earthquake records relevant to the regional or tectonic context, including both vertical and horizontal accelerations. Consequently, the Zipingpu example alone does not substantiate ATC/W’s broader inference for dam performance predictions at other locations, such as the RMFS scenario.

## <br>Appendix: Historical Earthquakes $(M_w\geq 6.0)$

{{< include /_slides/eventos.qmd >}}
::: {#fig-map}
<iframe src="map/index.html" width="100%" height="500px"></iframe>
Historical seismicity within a radius of 1,000 km from the project site, according the USGS and ISC global earthquake catalogs.
:::

## <br>References {.unnumbered}

:::{.references #refs}
:::
