
```{r include=TRUE}
CAP <-   "Annual Probability of Exceedence (AEP) for maximum horizontal spectral accelerations with 5%% critical damping  Sa(Tn) in [g] at different structural periods. Spectral ordinates were obtained assuming rock site conditions with Vs30 = %d  m/s."

Vs30_TARGET <- 760
ID_TARGET <- "gem"
p_TARGET <- "mean"
Vref_TARGET <- 760
root <- here::here()          
Sa_LOG = TRUE

```

:::{.panel-tabset .full-width }


#### $S_a(0)$ (PGA)

```{r ,eval=knitr::is_html_output(),include=knitr::is_html_output()}
#| label: fig-aep1
#| fig-cap: !expr CAP  |> sprintf(Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
Tn_TARGET <- 0

source(file.path(root,"psha/_fig/AEP_p.R"))
PLOT
```



#### $S_a(0.2)$ 

```{r ,eval=knitr::is_html_output(),include=knitr::is_html_output()}
#| label: fig-aep2
#| fig-cap: !expr CAP  |> sprintf(Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
Tn_TARGET <- 0.2

source(file.path(root,"psha/_fig/AEP_p.R"))
PLOT
```




#### $S_a(1.0)$ 

```{r ,eval=knitr::is_html_output(),include=knitr::is_html_output()}
#| label: fig-aep3
#| fig-cap: !expr CAP  |> sprintf(Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
Tn_TARGET <- 1.0

source(file.path(root,"psha/_fig/AEP_p.R"))
PLOT
```

:::
