```{r include=!knitr::is_html_output(),eval=!knitr::is_html_output()}
root <- here::here()          
```
:::{.panel-tabset .full-width }

#### Reference

```{r ,include=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
p_TARGET <- c("mean")
source(file.path(root,"psha/_tbl/IDm.R"))

TBL
```
#### `r IDg_gmdp[1]`

```{r ,include=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
p_TARGET <- c("mean")
IDg_TARGET <- IDg_gmdp[1]
source(file.path(root,"psha/_tbl/Ts_p.R"))

TBL
```


#### `r IDg_gmdp[2]`

```{r ,include=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
p_TARGET <- c("mean")
IDg_TARGET <- IDg_gmdp[2]
source(file.path(root,"psha/_tbl/Ts_p.R"))

TBL
```


#### `r IDg_gmdp[3]`

```{r ,include=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
p_TARGET <- c("mean")
IDg_TARGET <- IDg_gmdp[3]
source(file.path(root,"psha/_tbl/Ts_p.R"))
TBL
```


#### `r IDg_gmdp[4]`

```{r ,include=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
p_TARGET <- c("mean")
IDg_TARGET <- IDg_gmdp[4]
source(file.path(root,"psha/_tbl/Ts_p.R"))
TBL
```


#### `r IDg_gmdp[5]`

```{r ,include=TRUE,eval=TRUE,message=FALSE,warning=FALSE}
p_TARGET <- c("mean")
IDg_TARGET <- IDg_gmdp[5]
source(file.path(root,"psha/_tbl/Ts_p.R"))
TBL
```


:::





